name: SDK Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  AMOY_PROVIDER_URL: ${{ secrets.AMOY_PROVIDER_URL }}
  TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
  POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
  MAINNET_SIG_DEPLOYMENT_MNEMONIC: ${{ secrets.MAINNET_SIG_DEPLOYMENT_MNEMONIC }}
  SALT: ${{ secrets.SALT }}
  PNPM_VERSION: 9.1.4
  NODE_VERSION: 20.14

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.MERGE_BOT_APP_ID }}
          private_key: ${{ secrets.MERGE_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Config github actions user
        run: |
          git config --global user.name "compilot-release[bot]"
          git config --global user.email "137495321+compilot-release[bot]@users.noreply.github.com"

      - name: Bump versions and update changelog
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          lerna version --yes --changelog-preset=angular

      - name: Build
        env:
          AMOY_PROVIDER_URL: ${{ secrets.AMOY_PROVIDER_URL }}
          TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
          MAINNET_SIG_DEPLOYMENT_MNEMONIC: ${{ secrets.MAINNET_SIG_DEPLOYMENT_MNEMONIC }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SALT: ${{ secrets.SALT }}
        run: |
          pnpm run build:contracts
          pnpm --filter @compilot/sig-gating-contracts-sdk build
          pnpm --filter @compilot/tezos-sig-gating-contracts-sdk build

#      - name: Publish to private NPM
#        run: |
#          pnpm --filter @compilot/sig-gating-contracts publish --no-git-checks --registry https://npm.pkg.github.com/
#          pnpm --filter @compilot/sig-gating-contracts-sdk publish --no-git-checks --registry https://npm.pkg.github.com/
#          pnpm --filter @compilot/tezos-sig-gating-contracts-sdk publish --no-git-checks --registry https://npm.pkg.github.com/

      - name: Publish to public NPM
        env:
          NPMJS_COM_TOKEN: ${{ secrets.NPMJS_COM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPMJS_COM_TOKEN" > .npmrc

          pnpm --filter "@compilot/sig-gating-contracts" publish --access=public --no-git-checks --registry https://registry.npmjs.org/

          pnpm --filter "@compilot/sig-gating-contracts-sdk" publish --access=public --no-git-checks --registry https://registry.npmjs.org/
          
          pnpm --filter "@compilot/tezos-sig-gating-contracts-sdk" publish --access=public --no-git-checks --registry https://registry.npmjs.org/
