name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

env:
  AMOY_PROVIDER_URL: ${{ secrets.AMOY_PROVIDER_URL }}
  TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
  POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
  MAINNET_SIG_DEPLOYMENT_MNEMONIC: ${{ secrets.MAINNET_SIG_DEPLOYMENT_MNEMONIC }}
  SALT: ${{ secrets.SALT }}
  PNPM_VERSION: 9.1.4
  NODE_VERSION: 20.14

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-test-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ env.NPM_TOKEN }}

      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Check for changes files
        run: |
          git restore .npmrc
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "Changed files detected, run lint locally"
            exit 1
          else
            echo "No new files, exiting cleanly"
          fi

      - name: Build
        env:
          AMOY_PROVIDER_URL: ${{ secrets.AMOY_PROVIDER_URL }}
          TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          POLYGON_MAINNET_PROVIDER_URL: ${{ secrets.POLYGON_MAINNET_PROVIDER_URL }}
          MAINNET_SIG_DEPLOYMENT_MNEMONIC: ${{ secrets.MAINNET_SIG_DEPLOYMENT_MNEMONIC }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SALT: ${{ secrets.SALT }}
        run: |
          pnpm run build:contracts
          pnpm --filter @nexeraprotocol/nexera-id-sig-gating-contracts-sdk build
